- hosts: localhost
  connection: local
  tasks:
    - name: Change mesos-init-settings.sh permissions
      file:
        path: /usr/local/bin/mesos-init-settings.sh
        mode: '0755'

    - name: Download wait-for-it.sh
      get_url:
        url: https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
        dest: /usr/local/bin/wait-for-it
        mode: '0441'

    - name: Install the Mesosphere rpm
      shell: rpm -Uvh http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm

    - name: Install the latest version of Mesos
      yum:
        name: mesos
        state: latest
        disable_gpg_check: yes

    - name: Add the Zookeeper's address
      lineinfile:
        regexp: "^zk"
        line: zk://mesos.bytesb8.io:2181/mesos
        path: /etc/mesos/zk

    - name: Add the Mesos hostname
      lineinfile:
        regexp: "^zk"
        line: mesos.bytesb8.io
        path: "/etc/mesos-slave/hostname"
        create: yes
