- hosts: localhost
  connection: local
  tasks:
    - name: Install the Mesosphere rpm
      shell: rpm -Uvh http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm

    - name: Install the latest version of Mesos
      yum:
        name: "{{ packages }}"
        state: latest
        disable_gpg_check: yes
      vars:
        packages:
          - mesos
          - mesosphere-zookeeper

    - name: Add the zookeeper's address
      lineinfile:
        regexp: "^zk"
        line: zk://mesos.bytesb8.io:2181/mesos
        path: /etc/mesos/zk

    - name: Add a line for the master to wait for available named Zookeeper
      lineinfile:
        insertbefore: "ExecStart=/usr/bin/mesos-init-wrapper master"
        line: ExecStartPre=wait-for-it --timeout=6000 mesos.bytesb8.io:2181
        path: /etc/systemd/system/multi-user.target.wants/mesos-master.service

    - name: Add a line for the agent to wait for available named Zookeeper
      lineinfile:
        insertbefore: "ExecStart=/usr/bin/mesos-init-wrapper slave"
        line: ExecStartPre=wait-for-it --timeout=6000 mesos.bytesb8.io:2181
        path: /etc/systemd/system/multi-user.target.wants/mesos-slave.service
