- hosts: localhost
  connection: local
  tasks:
    - name: Install the latest version of Marathon
      yum:
        name: marathon
        state: latest
        disable_gpg_check: yes

    - name: Add the zookeeper's address
      blockinfile:
        path: /etc/default/marathon
        block: |
          MARATHON_MASTER=zk://mesos.bytesb8.io:2181/mesos
          MARATHON_HOSTNAME=marathon.bytesb8.io
        create: yes
